### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by DanielDornhardt** [mrauhu/meteor-uwebsockets#1]
Hi, I tried to grok it but I can't, I get this error when I come to the point in the docs to install the stream-server-uws - package:

```
> meteor add stream-server-uws

This project is already at Meteor 1.10.2, the latest release.
=> Errors while upgrading packages:

While selecting package versions:
error: No version of socket-stream-client satisfies all constraints: @=0.2.3, @~0.3.0
Constraints on package "socket-stream-client":
* socket-stream-client@=0.2.3 <- top level
* socket-stream-client@~0.3.0 <- top level
* socket-stream-client@0.2.0 <- ddp-client 2.3.3 <- ddp 1.4.0 <- accounts-base 1.6.0 <- accounts-password 1.6.0
* socket-stream-client@0.2.0 <- ddp-client 2.3.3 <- ddp 1.4.0 <- accounts-password 1.6.0
```

**Comment by mrauhu** [comment]
Greetings @DanielDornhardt 

Thanks for report.

I'm added support for the Meteor 1.10.2.

Please update Git submodules to get latest versions of packages:

```
git submodule update --recursive --remote
```

**Comment by DanielDornhardt** [comment]
Hello @mrauhu , I just tried it again and what can I say, it seems like it's working!

Thank you very much & have a good time, thank you for giving back to the community.
