### ISSUE TITLE
Please stop using my trademarks

### ISSUE THREAD

**Issue by ghost** [mrauhu/meteor-uwebsockets#4]
I believe I've told you before,

This thing is using a three year old fork (legally a derivative work) that is not "uWebSockets". They call it cWS, the fork, and so should you. The fork in question is not the original work and per license terms **must not be misrepresented as being the original** thing. Remember that you're licensing my IP as per my terms, and I'm currently not happy with how you mix the two projects.

Please change naming and headers to clearly and accurately refer to this "cWS" thing instead.

Also I would not like to be listed under "thanks to".

**Comment by ghost** [comment]
Thanks, this is a lot better. You also have the description.

**Comment by mrauhu** [comment]
@alexhultman-2fa Removed mentions and renamed the repository, also fixed description and tags.
